spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=mi_microservicio
spring.datasource.password=micontra123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

aws.s3.bucket-name=microservicio-guias-duoc
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.session-token=${AWS_SESSION_TOKEN}

server.port=8080
spring.jackson.serialization.indent-output=true
